

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://Omniscient:1234@db:5432/postgres
    depends_on:
      - db
      - mosquitto
    env_file:
      - .env

  db:
    container_name: postgres_db  # You can leave this as-is
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: Omniscient
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto_broker
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "C:/Program Files/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro"
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

volumes:
  postgres_data:
